services:
  mongo:
    image: mongo:6.0
    container_name: vibemap-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  server:
    container_name: vibemap-server
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    command: node server/server.js
    ports:
      - "5000:5000"
    depends_on:
      - mongo
